#!/bin/bash 
set -o pipefail

for case in `ls test/*.cmdLine`; do
   base=`basename $case .cmdLine`
   echo 
   echo "RUNING: hello" `cat $case`
   echo "------------------------"

   hello `cat $case` | diff -q - test/${base}.out
   res=$(( ${PIPESTATUS[0]}+${PIPESTATUS[1]} ))
   echo ${res}
   if [ ${res} -eq 0 ]; then
      echo 'Success'
   else 
      echo 'Failed'
      echo "Output should be"
      cat test/${base}.out
      echo
      echo "but was "
      hello `cat $case`
      exit 1
   fi
   echo
done

exit 0
